name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./reservation-platform-development/pom.xml
          mvn clean package -f ./partnership-management/pom.xml
          mvn clean package -f ./marketing-and-advertising/pom.xml
          mvn clean package -f ./customer-support-and-assistance/pom.xml
          mvn clean package -f ./financial-management/pom.xml

      - name: Docker Build and push for ReservationPlatformDevelopment
        uses: docker/build-push-action@v4
        with:
          context: ./reservation-platform-development
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/reservation-platform-development:latest
            ghcr.io/${{ github.repository }}/reservation-platform-development:${{ github.ref_name }}
            
      - name: Docker Build and push for PartnershipManagement
        uses: docker/build-push-action@v4
        with:
          context: ./partnership-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/partnership-management:latest
            ghcr.io/${{ github.repository }}/partnership-management:${{ github.ref_name }}
            
      - name: Docker Build and push for MarketingAndAdvertising
        uses: docker/build-push-action@v4
        with:
          context: ./marketing-and-advertising
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/marketing-and-advertising:latest
            ghcr.io/${{ github.repository }}/marketing-and-advertising:${{ github.ref_name }}
            
      - name: Docker Build and push for CustomerSupportAndAssistance
        uses: docker/build-push-action@v4
        with:
          context: ./customer-support-and-assistance
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/customer-support-and-assistance:latest
            ghcr.io/${{ github.repository }}/customer-support-and-assistance:${{ github.ref_name }}
            
      - name: Docker Build and push for FinancialManagement
        uses: docker/build-push-action@v4
        with:
          context: ./financial-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/financial-management:latest
            ghcr.io/${{ github.repository }}/financial-management:${{ github.ref_name }}
            
