apiVersion: v1
kind: Service
metadata:
  name: customer-support-and-assistance
  labels:
    app: customer-support-and-assistance
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: customer-support-and-assistance