apiVersion: v1
kind: Service
metadata:
  name: marketing-and-advertising
  labels:
    app: marketing-and-advertising
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: marketing-and-advertising