server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: reservation-platform-development
          uri: http://localhost:8082
          predicates:
            - Path=/users/**, /hotels/**, /reservations/**, 
        - id: partnership-management
          uri: http://localhost:8083
          predicates:
            - Path=/hotelPartners/**, /travelAgencies/**, 
        - id: marketing-and-advertising
          uri: http://localhost:8084
          predicates:
            - Path=/marketingCampaigns/**, 
        - id: customer-support-and-assistance
          uri: http://localhost:8085
          predicates:
            - Path=/customerSupportTickets/**, 
        - id: financial-management
          uri: http://localhost:8086
          predicates:
            - Path=/financialReports/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reservation-platform-development
          uri: http://reservationPlatformDevelopment:8080
          predicates:
            - Path=/users/**, /hotels/**, /reservations/**, 
        - id: partnership-management
          uri: http://partnershipManagement:8080
          predicates:
            - Path=/hotelPartners/**, /travelAgencies/**, 
        - id: marketing-and-advertising
          uri: http://marketingAndAdvertising:8080
          predicates:
            - Path=/marketingCampaigns/**, 
        - id: customer-support-and-assistance
          uri: http://customerSupportAndAssistance:8080
          predicates:
            - Path=/customerSupportTickets/**, 
        - id: financial-management
          uri: http://financialManagement:8080
          predicates:
            - Path=/financialReports/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
