apiVersion: v1
kind: Service
metadata:
  name: reservation-platform-development
  labels:
    app: reservation-platform-development
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: reservation-platform-development